---
title: "Computational Methods for Environmental Engineers - Course Notes"
author: "K Todd-Brown (ktoddbrown@ufl.edu)"
date: "9/28/2020"
site: "bookdown::bookdown_site"
output:
  bookdown::gitbook: default
documentclass: book
---

# Why do we care about computational methods? {-}

Computational methods could be one of the most useful courses you have ever taken.
As an engineer, scientist or technical staff, you will probably have to collect and/or analyize data then use this to support decisions that will affect your clients and community.
The skills in this class will help you do this in a way that is transparent and reproducable. 

We are going to focus on two things this semester 1) data cleaning and visualization, and 2) developing numerical models.
Historically computational methods has focused on algorithms to solve numerical integration and optimization problems. 
We will do some of this over the course of the semester but in practice many of you will never actually need to write a forward-difference solver, instead relying on libraries and packages that are already developed.
This historically approach also ignores the new developments in data analysis workflows that have relatively recently come into common practice.

## Other references

There are lots of excellent references on R and other topics we'll be covering this semester but some that you might want to pay special attention to are:

  + Venables, WN, DM Smith, and the R Core Team, **An Introduction to R**, [R, version 4.0.2 (2020-06-22)],  https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf
    - Intro to R is a short classic that is updated with each major release of R. Want the basics in a short format? Go here.
  + Michonneau, F, A Fournier, and others, **Data Carpentry: Data Analysis and Visualization in R for Ecologists**, https://datacarpentry.org/R-ecology-lesson/
    - Lesson plans for the data carpentry R workshop are an excellent on-ramp to learning R. We'll be going back and forth in these lessons over the semester. These can be an excellent refresher or a way to peak head.
  + Hadley Wickham, **Advanced R**, 2nd edition (2019). https://adv-r.hadley.nz/ (ISBN-13: 978-0815384571)
    - Advanced R is the go to book when you want to go deeper. If you want to know why something is the way it is in R this book probably has the answer, but it's not always beginner friendly.